// <auto-generated />
using System;
using DeliverIT.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Deliverit.Database.Migrations
{
    [DbContext(typeof(DeliveritDbContext))]
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
    [Migration("20210412172914_Initial")]
=======
    [Migration("20210414095013_Initial")]
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeliverIT.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36049406-10ba-499d-916b-063422046239"),
                            CityId = new Guid("e99abf10-63e9-4212-9053-87cb1d80763e"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 489, DateTimeKind.Utc).AddTicks(6370),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(7115),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            StreetName = "Ramon Berenguer El Vell 1"
                        },
                        new
                        {
                            Id = new Guid("ac2fee3a-f76e-4d94-aa42-d85b4bb45299"),
                            CityId = new Guid("e422b2de-f54d-4a4e-9259-0f3f4033f93d"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 489, DateTimeKind.Utc).AddTicks(7687),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(7812),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            StreetName = "Zeughofstraße 20"
                        },
                        new
                        {
                            Id = new Guid("b1347388-583d-4324-870a-e487e61ef483"),
                            CityId = new Guid("7fdbb1a0-9f76-4b63-aab4-901c61591336"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 489, DateTimeKind.Utc).AddTicks(7709),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(7830),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            StreetName = "Rue La Boetie 7"
                        },
                        new
                        {
                            Id = new Guid("97fa423a-a144-4d67-97f5-4211c2758dc5"),
                            CityId = new Guid("8bf95d78-e5ac-495d-ab67-14b60f644b70"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 489, DateTimeKind.Utc).AddTicks(7712),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(7838),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            StreetName = "Liepkalnio 117"
                        },
                        new
                        {
                            Id = new Guid("5fd8c18f-6885-488e-af8c-ff06901a7d37"),
                            CityId = new Guid("e99abf10-63e9-4212-9053-87cb1d80763e"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 489, DateTimeKind.Utc).AddTicks(7716),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(7838),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            StreetName = "Gran Via De Les Corts Catalanes 105"
                        },
                        new
                        {
                            Id = new Guid("da703902-00bc-47da-b950-4fa730494d4e"),
                            CityId = new Guid("e99abf10-63e9-4212-9053-87cb1d80763e"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 489, DateTimeKind.Utc).AddTicks(7723),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(7855),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            StreetName = "Passatge De Bocabella 11"
                        });
                });

            modelBuilder.Entity("DeliverIT.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c803ff6d-efb9-401a-81d8-7e9df0fcd4c1"),
                            AddressId = new Guid("b1347388-583d-4324-870a-e487e61ef483"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 490, DateTimeKind.Utc).AddTicks(786),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 268, DateTimeKind.Utc).AddTicks(341),
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Email = "isabelle.huppert@gmail.com",
                            FirstName = "Isabelle",
                            IsDeleted = false,
                            LastName = "Huppert"
                        },
                        new
                        {
                            Id = new Guid("5adb06fe-fca4-4347-b1ea-118c55e17331"),
                            AddressId = new Guid("97fa423a-a144-4d67-97f5-4211c2758dc5"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 490, DateTimeKind.Utc).AddTicks(4681),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 268, DateTimeKind.Utc).AddTicks(1442),
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Email = "lukas.petr@gmail.com",
                            FirstName = "Lukas",
                            IsDeleted = false,
                            LastName = "Petrauskas"
                        });
                });

            modelBuilder.Entity("DeliverIT.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2c26c93-d589-4b05-850b-fbf21c59c84d"),
                            AddressId = new Guid("5fd8c18f-6885-488e-af8c-ff06901a7d37"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 490, DateTimeKind.Utc).AddTicks(6001),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 268, DateTimeKind.Utc).AddTicks(2174),
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Email = "fer.trujillo@gmail.com",
                            FirstName = "Fermin",
                            IsDeleted = false,
                            LastName = "Trujillo"
                        },
                        new
                        {
                            Id = new Guid("facdefb9-19df-42b3-9d3d-6524076e152f"),
                            AddressId = new Guid("da703902-00bc-47da-b950-4fa730494d4e"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 490, DateTimeKind.Utc).AddTicks(8346),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 268, DateTimeKind.Utc).AddTicks(3249),
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Email = "a.rivas@gmail.com",
                            FirstName = "Amador",
                            IsDeleted = false,
                            LastName = "Rivas"
                        });
                });

            modelBuilder.Entity("DeliverIT.Models.Parcel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ShipmentId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Parcels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("198457ae-236c-4592-90af-3ca2302a8737"),
                            CategoryId = new Guid("1db0c76c-ab76-4105-be89-3af983f6f137"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 490, DateTimeKind.Utc).AddTicks(9575),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 268, DateTimeKind.Utc).AddTicks(3954),
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            CustomerId = new Guid("c803ff6d-efb9-401a-81d8-7e9df0fcd4c1"),
                            EmployeeId = new Guid("d2c26c93-d589-4b05-850b-fbf21c59c84d"),
                            IsDeleted = false,
                            ShipmentId = new Guid("ce465c59-4866-4905-bdbd-943a26f59fdd"),
                            WarehouseId = new Guid("f15b5cf4-6eb6-4e5a-b84f-297e16c206ba"),
                            Weight = 10
                        },
                        new
                        {
                            Id = new Guid("28ae32a1-10a4-4aef-b262-3baaa1102753"),
                            CategoryId = new Guid("72280df2-7d81-4ec6-936a-51e19aabf7ff"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 491, DateTimeKind.Utc).AddTicks(3863),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 268, DateTimeKind.Utc).AddTicks(5709),
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            CustomerId = new Guid("5adb06fe-fca4-4347-b1ea-118c55e17331"),
                            EmployeeId = new Guid("facdefb9-19df-42b3-9d3d-6524076e152f"),
                            IsDeleted = false,
                            ShipmentId = new Guid("e2a2c29b-b7f4-458a-9cde-4a70717607c8"),
                            WarehouseId = new Guid("988a4201-8c55-42fc-b2a6-e08d1abe6693"),
                            Weight = 5
                        });
                });

            modelBuilder.Entity("DeliverIT.Models.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Shipments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ce465c59-4866-4905-bdbd-943a26f59fdd"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            ArrivalDate = new DateTime(2021, 4, 19, 17, 29, 13, 491, DateTimeKind.Utc).AddTicks(5635),
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 491, DateTimeKind.Utc).AddTicks(5037),
                            DepartureDate = new DateTime(2021, 4, 12, 17, 29, 13, 491, DateTimeKind.Utc).AddTicks(5037),
=======
                            ArrivalDate = new DateTime(2021, 4, 21, 9, 50, 13, 268, DateTimeKind.Utc).AddTicks(6784),
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 268, DateTimeKind.Utc).AddTicks(6449),
                            DepartureDate = new DateTime(2021, 4, 14, 9, 50, 13, 268, DateTimeKind.Utc).AddTicks(6449),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            StatusId = new Guid("917f8117-d392-4f64-81fb-48415f80f77e"),
                            WarehouseId = new Guid("f15b5cf4-6eb6-4e5a-b84f-297e16c206ba")
                        },
                        new
                        {
                            Id = new Guid("e2a2c29b-b7f4-458a-9cde-4a70717607c8"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            ArrivalDate = new DateTime(2021, 4, 17, 17, 29, 13, 491, DateTimeKind.Utc).AddTicks(7575),
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 491, DateTimeKind.Utc).AddTicks(7553),
                            DepartureDate = new DateTime(2021, 4, 12, 17, 29, 13, 491, DateTimeKind.Utc).AddTicks(7553),
=======
                            ArrivalDate = new DateTime(2021, 4, 19, 9, 50, 13, 268, DateTimeKind.Utc).AddTicks(7868),
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 268, DateTimeKind.Utc).AddTicks(7842),
                            DepartureDate = new DateTime(2021, 4, 14, 9, 50, 13, 268, DateTimeKind.Utc).AddTicks(7842),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            StatusId = new Guid("858ac364-d94f-414c-bbea-a0f5b8679b3d"),
                            WarehouseId = new Guid("988a4201-8c55-42fc-b2a6-e08d1abe6693")
                        });
                });

            modelBuilder.Entity("DeliverIT.Models.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f15b5cf4-6eb6-4e5a-b84f-297e16c206ba"),
                            AddressId = new Guid("36049406-10ba-499d-916b-063422046239"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 489, DateTimeKind.Utc).AddTicks(8941)
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(9266),
                            IsDeleted = false
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                        },
                        new
                        {
                            Id = new Guid("988a4201-8c55-42fc-b2a6-e08d1abe6693"),
                            AddressId = new Guid("ac2fee3a-f76e-4d94-aa42-d85b4bb45299"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 489, DateTimeKind.Utc).AddTicks(9627)
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(9636),
                            IsDeleted = false
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                        });
                });

            modelBuilder.Entity("Deliverit.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(35)")
                        .HasMaxLength(35);

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1db0c76c-ab76-4105-be89-3af983f6f137"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 489, DateTimeKind.Utc).AddTicks(2078),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(4999),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("df79ccb6-1f56-41da-9f8f-df2f92a468bb"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 489, DateTimeKind.Utc).AddTicks(2895),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(5343),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("7aeb290e-3592-4128-a77a-1a6db6fd81f5"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 489, DateTimeKind.Utc).AddTicks(2910),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(5352),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Name = "Medical"
                        },
                        new
                        {
                            Id = new Guid("72280df2-7d81-4ec6-936a-51e19aabf7ff"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 489, DateTimeKind.Utc).AddTicks(2910),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(5352),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("Deliverit.Models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(55)")
                        .HasMaxLength(55);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e99abf10-63e9-4212-9053-87cb1d80763e"),
                            CountryId = new Guid("2a84fe90-6605-4052-8a49-e7251af05754"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 486, DateTimeKind.Utc).AddTicks(2452),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 265, DateTimeKind.Utc).AddTicks(1619),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = new Guid("e422b2de-f54d-4a4e-9259-0f3f4033f93d"),
                            CountryId = new Guid("afbcad66-1a0a-49f2-9e9c-2c61ded8ae08"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 486, DateTimeKind.Utc).AddTicks(5325),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 265, DateTimeKind.Utc).AddTicks(2651),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = new Guid("7fdbb1a0-9f76-4b63-aab4-901c61591336"),
                            CountryId = new Guid("72ec653b-aeb1-42fc-bcd1-153f005b1cd4"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 486, DateTimeKind.Utc).AddTicks(5351),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 265, DateTimeKind.Utc).AddTicks(2677),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Name = "Paris"
                        },
                        new
                        {
                            Id = new Guid("8bf95d78-e5ac-495d-ab67-14b60f644b70"),
                            CountryId = new Guid("c4b3bb07-585f-412b-9f5f-f423928015d4"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 486, DateTimeKind.Utc).AddTicks(5355),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 265, DateTimeKind.Utc).AddTicks(2677),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Name = "Vilnius"
                        });
                });

            modelBuilder.Entity("Deliverit.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(55)")
                        .HasMaxLength(55);

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a84fe90-6605-4052-8a49-e7251af05754"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 488, DateTimeKind.Utc).AddTicks(8778),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(2772),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("afbcad66-1a0a-49f2-9e9c-2c61ded8ae08"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 488, DateTimeKind.Utc).AddTicks(9485),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(3562),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("72ec653b-aeb1-42fc-bcd1-153f005b1cd4"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 488, DateTimeKind.Utc).AddTicks(9496),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(3571),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("c4b3bb07-585f-412b-9f5f-f423928015d4"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 488, DateTimeKind.Utc).AddTicks(9500),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(3571),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Name = "Lithuania"
                        });
                });

            modelBuilder.Entity("Deliverit.Models.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(35)")
                        .HasMaxLength(35);

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = new Guid("917f8117-d392-4f64-81fb-48415f80f77e"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 489, DateTimeKind.Utc).AddTicks(4536),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(6074),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Name = "Preparing"
                        },
                        new
                        {
                            Id = new Guid("858ac364-d94f-414c-bbea-a0f5b8679b3d"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 489, DateTimeKind.Utc).AddTicks(5192),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(6393),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Name = "OnTheWay"
                        },
                        new
                        {
                            Id = new Guid("84568d3c-04df-47c3-9ad8-216b1d664166"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 489, DateTimeKind.Utc).AddTicks(5207),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(6410),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Name = "Completed"
                        },
                        new
                        {
                            Id = new Guid("b31754e2-82fc-4862-ad20-9331a87537eb"),
<<<<<<< HEAD:DeliverIT/DeliverIT.Database/Migrations/20210412172914_Initial.Designer.cs
                            CreatedOn = new DateTime(2021, 4, 12, 17, 29, 13, 489, DateTimeKind.Utc).AddTicks(5211),
=======
                            CreatedOn = new DateTime(2021, 4, 14, 9, 50, 13, 267, DateTimeKind.Utc).AddTicks(6410),
                            IsDeleted = false,
>>>>>>> Boryana:DeliverIT/DeliverIT.Database/Migrations/20210414095013_Initial.Designer.cs
                            Name = "Canceled"
                        });
                });

            modelBuilder.Entity("DeliverIT.Models.Address", b =>
                {
                    b.HasOne("Deliverit.Models.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliverIT.Models.Customer", b =>
                {
                    b.HasOne("DeliverIT.Models.Address", "Address")
                        .WithMany("Customers")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliverIT.Models.Employee", b =>
                {
                    b.HasOne("DeliverIT.Models.Address", "Address")
                        .WithMany("Employees")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliverIT.Models.Parcel", b =>
                {
                    b.HasOne("Deliverit.Models.Category", "Category")
                        .WithMany("Parcels")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliverIT.Models.Customer", "Customer")
                        .WithMany("Parcels")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliverIT.Models.Employee", "Employee")
                        .WithMany("Parcels")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliverIT.Models.Shipment", "Shipment")
                        .WithMany("Parcels")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DeliverIT.Models.Warehouse", "Warehouse")
                        .WithMany("Parcels")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliverIT.Models.Shipment", b =>
                {
                    b.HasOne("Deliverit.Models.Status", "Status")
                        .WithMany("Shipments")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliverIT.Models.Warehouse", "Warehouse")
                        .WithMany("Shipments")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeliverIT.Models.Warehouse", b =>
                {
                    b.HasOne("DeliverIT.Models.Address", "Address")
                        .WithMany("Warehouses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Deliverit.Models.City", b =>
                {
                    b.HasOne("Deliverit.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
